service: data-config-admin-sync

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-southeast-2
  logRetentionInDays: 7
  environment:
    GITHUB_TOKEN: ${env:GITHUB_TOKEN, ''}
    GITHUB_REPO: s2265681/data-config-admin
    S3_BUCKET: rock-service-data
  # IAM权限将由 DynamicIamPermissionsPlugin 动态生成

functions:
  # S3到GitHub同步Lambda函数 - 事件配置将由插件动态生成
  s3ToGithubSync:
    handler: handlers/s3-to-github.handler
    logRetentionInDays: 7
    # events 配置将由 DynamicS3EventsPlugin 动态生成

plugins:
  - serverless-dotenv-plugin
  - ./plugins/dynamic-s3-events.js      # 动态生成S3事件配置
  - ./plugins/dynamic-iam-permissions.js # 动态生成IAM权限配置

custom:
  dotenv:
    path: .env
    include:
      - GITHUB_TOKEN
      - GITHUB_REPO
      - S3_BUCKET
  
  # 动态生成S3资源ARN
  s3ResourceArns: ${file(./utils/generate-s3-arns.js)} 