service: data-config-admin-sync

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-southeast-2
  logRetentionInDays: 7
  environment:
    GITHUB_TOKEN: ${env:GITHUB_TOKEN, ''}
    GITHUB_REPO: s2265681/data-config-admin
    S3_BUCKET: rock-service-data
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:GetObject
            - s3:PutObject
            - s3:DeleteObject
          Resource: 
            - arn:aws:s3:::rock-service-data/config/staging/*
            - arn:aws:s3:::rock-service-data/config/production/*
            - arn:aws:s3:::rock-service-data/config2/staging/*
            - arn:aws:s3:::rock-service-data/config2/production/*
            - arn:aws:s3:::rock-service-data/config3/staging/*
            - arn:aws:s3:::rock-service-data/config3/production/*
        - Effect: Allow
          Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
            - logs:DeleteLogGroup
          Resource: "*"

functions:
  # 多文件同步Lambda函数 - 事件配置将由插件动态生成
  s3ToGithubMultiSync:
    handler: handlers/s3-to-github-multi.handler
    logRetentionInDays: 7
    # events 配置将由 DynamicS3EventsPlugin 动态生成

plugins:
  - serverless-dotenv-plugin
  - ./plugins/dynamic-s3-events.js

custom:
  dotenv:
    path: .env
    include:
      - GITHUB_TOKEN
      - GITHUB_REPO
      - S3_BUCKET
  
  # 动态生成S3资源ARN
  s3ResourceArns: ${file(./utils/generate-s3-arns.js)} 