service: data-config-admin-sync

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-southeast-2
  logRetentionInDays: 7
  environment:
    GITHUB_TOKEN: ${env:GITHUB_TOKEN, ''}
    GITHUB_REPO: s2265681/data-config-admin
    S3_BUCKET: rock-service-data
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:GetObject
            - s3:PutObject
            - s3:DeleteObject
          Resource: 
            - arn:aws:s3:::rock-service-data/config/staging/*
            - arn:aws:s3:::rock-service-data/config/production/*
        - Effect: Allow
          Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
            - logs:DeleteLogGroup
          Resource: "*"

functions:
  # 只保留多文件同步Lambda函数 - 处理所有JSON文件
  s3ToGithubMultiSync:
    handler: handlers/s3-to-github-multi.handler
    logRetentionInDays: 7
    events:
      - s3:
          bucket: rock-service-data
          event: s3:ObjectCreated:*
          rules:
            - prefix: config/staging/
            - suffix: .json
          existing: true
      - s3:
          bucket: rock-service-data
          event: s3:ObjectRemoved:*
          rules:
            - prefix: config/staging/
            - suffix: .json
          existing: true
      - s3:
          bucket: rock-service-data
          event: s3:ObjectCreated:*
          rules:
            - prefix: config/production/
            - suffix: .json
          existing: true
      - s3:
          bucket: rock-service-data
          event: s3:ObjectRemoved:*
          rules:
            - prefix: config/production/
            - suffix: .json
          existing: true

plugins:
  - serverless-dotenv-plugin

custom:
  dotenv:
    path: .env
    include:
      - GITHUB_TOKEN
      - GITHUB_REPO
      - S3_BUCKET 