name: GitHub to S3 Multi-File Sync

on:
  push:
    branches: [ staging ]
    paths:
      - 'configuration/**'
      - 'config/folders.json'
  workflow_dispatch:

jobs:
  sync-to-s3:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-2
        
    - name: Set environment variables
      run: |
        echo "S3_BUCKET=${{ secrets.S3_BUCKET }}" >> $GITHUB_ENV
        echo "AWS_REGION=ap-southeast-2" >> $GITHUB_ENV
        echo "GITHUB_SHA=${{ github.sha }}" >> $GITHUB_ENV
        
    - name: Test AWS connection
      run: |
        aws sts get-caller-identity --region ap-southeast-2
        echo "AWS connection test successful"
        
    - name: Validate configuration
      run: npm run manage-folders validate
      
    - name: Sync folders to S3
      run: npm run sync-to-s3
      env:
        AWS_REGION: ap-southeast-2
        S3_BUCKET: ${{ secrets.S3_BUCKET }}
        GITHUB_SHA: ${{ github.sha }}
        
    - name: Monitor sync status
      run: npm run monitor 