name: Sync to S3

on:
  push:
    branches:
      - staging
    paths:
      - 'test.json'
  pull_request:
    branches:
      - staging
    paths:
      - 'test.json'

jobs:
  sync-to-s3:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true)
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2
          
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Sync to S3
        run: npm run sync-to-s3
        env:
          S3_BUCKET: rock-service-data
          S3_KEY: config/staging/test.json
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Verify sync
        run: |
          echo "验证S3同步..."
          aws s3 ls s3://rock-service-data/config/staging/test.json 